<script setup lang="ts">
import { computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ArrowLeft, AlertTriangle, CheckCircle2, FileText, Lightbulb, ShieldCheck, Sparkles } from 'lucide-vue-next'

defineOptions({ name: 'SkillDetail' })

type SkillDetail = { id: string; name: string; status: string; version: string; updatedAt: string; owner: string; scene: string; description: string; skillPoints: string[]; docRaw: string; boundaries: string[] }
const route = useRoute()
const router = useRouter()
const skillDetails: Record<string, SkillDetail> = {
  'skill-report-writer': { id: 'skill-report-writer', name: '报告生成 Skill', status: '启用', version: 'v0.1.0', updatedAt: '2026-04-20 11:00', owner: 'AI 平台 / 报告生成 Agent', scene: '安全生产报告、整改报告、巡检分析报告', description: '把报告生成能力作为一份可阅读、可维护的 Skill 文档承接，用于说明能力边界、适用场景、生成规则和演示路径。', skillPoints: ['报告模板选择', 'Markdown 报告生成', 'NL2SQL 数据引用', '失败兜底提示', '右侧文档预览'], docRaw: '# 报告生成 Skill\n\n## 能力说明\n\n用于将用户输入、报告模板和可选 NL2SQL 数据结果组合为结构化 Markdown 报告。\n\n## 使用路径\n\n- 在首页选择「报告生成 Agent」\n- 输入报告需求后回车\n- 系统创建 Markdown 文档并打开右侧预览\n\n## 评审关注\n\n- 报告分屏不是选择 Agent 后立即出现，而是在开始生成后打开\n- 右侧预览可以关闭，关闭后恢复单屏\n- 当前阶段以 Markdown 文档为主，不做复杂 Word 在线排版', boundaries: ['不做复杂在线文档编辑器', '不做复杂 Word 排版', '不做模板市场', '不做跨系统多数据融合'] },
  'skill-nl2sql-governance': { id: 'skill-nl2sql-governance', name: 'NL2SQL 增强 Skill', status: '启用', version: 'v0.1.0', updatedAt: '2026-04-20 11:20', owner: 'AI 平台 / NL2SQL Agent', scene: '自然语言问数、指标解释、查询口径兜底', description: '将 NL2SQL 增强能力整理成 Skill 文档，用于描述 Case、专有名词和单数据源如何参与问数链路。', skillPoints: ['Good / Bad Case 参考', '专有名词别名映射', '单 JDBC 数据源', '查询口径解释', '失败提示兜底'], docRaw: '# NL2SQL 增强 Skill\n\n## 能力说明\n\n用于在问数前读取 Case、术语和单数据源配置，辅助生成 SQL 与口径解释。\n\n## 使用路径\n\n- 在系统设置中维护 NL2SQL 配置\n- 在首页通过 NL2SQL Agent 发起问数\n- Agent 根据 Case、术语、数据源状态给出查询说明\n\n## 本期范围\n\n只做单数据源，不做多数据源和跨库查询。', boundaries: ['不做多数据源', '不做跨库查询', '不做自动 SQL 优化', '不做多轮复杂推理'] },
}
const detail = computed(() => skillDetails[String(route.params.id)] || skillDetails['skill-report-writer'])
function escapeHtml(text: string) { return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;') }
function renderMarkdown(text: string) { return escapeHtml(text).replace(/^# (.*)$/gm, '<h1 class="mb-3 text-2xl font-bold text-slate-950">$1</h1>').replace(/^## (.*)$/gm, '<h2 class="mb-2 mt-5 text-base font-semibold text-slate-900">$1</h2>').replace(/^- (.*)$/gm, '<li class="ml-5 list-disc text-sm leading-7 text-slate-700">$1</li>').replace(/\n/g, '<br />') }
</script>

<template>
  <div class="space-y-5">
    <div class="rounded-[28px] border border-sky-200/70 bg-white/80 p-6 shadow-[0_22px_60px_rgba(14,116,144,0.08)] backdrop-blur-xl">
      <button type="button" @click="router.push('/mcp')" class="mb-5 inline-flex items-center gap-2 rounded-xl bg-white/80 px-3 py-2 text-xs font-semibold text-slate-800 ring-1 ring-sky-200/70 transition hover:bg-sky-50"><ArrowLeft class="h-4 w-4" /> 返回 AI 技能</button>
      <div class="flex flex-wrap items-start justify-between gap-5"><div class="min-w-0"><div class="flex flex-wrap items-center gap-3"><span class="inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-br from-sky-500 to-blue-600 text-white shadow-[0_16px_40px_rgba(37,99,235,0.22)]"><Sparkles class="h-5 w-5" /></span><div><h1 class="m-0 text-3xl font-semibold tracking-tight text-slate-950">{{ detail.name }}</h1><div class="mt-1 text-xs text-slate-500">{{ detail.owner }} · {{ detail.updatedAt }}</div></div></div><p class="mt-4 max-w-4xl text-sm leading-7 text-slate-600">{{ detail.description }}</p></div><div class="flex flex-wrap gap-2"><span class="rounded-full bg-sky-50 px-3 py-1 text-xs font-semibold text-sky-700 ring-1 ring-sky-200">Skill 文档</span><span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700 ring-1 ring-emerald-200">{{ detail.status }}</span><span class="rounded-full bg-white px-3 py-1 text-xs font-semibold text-slate-700 ring-1 ring-slate-200">{{ detail.version }}</span></div></div>
    </div>
    <div class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><section class="space-y-5"><div class="rounded-[28px] border border-sky-200/70 bg-white/85 p-6 shadow-[0_18px_44px_rgba(14,116,144,0.06)]"><div class="mb-4 flex items-center gap-2 text-sm font-semibold text-slate-900"><FileText class="h-4 w-4 text-sky-600" /> Skill.md 文档</div><article class="rounded-2xl bg-gradient-to-br from-white to-sky-50/70 p-5 text-slate-700 ring-1 ring-sky-200/70" v-html="renderMarkdown(detail.docRaw)" /></div></section><aside class="space-y-5"><div class="rounded-[24px] border border-sky-200/70 bg-white/85 p-5 shadow-[0_18px_44px_rgba(14,116,144,0.06)]"><div class="mb-4 flex items-center gap-2 text-sm font-semibold text-slate-900"><Lightbulb class="h-4 w-4 text-sky-600" /> 核心技能点</div><div class="space-y-2"><div v-for="item in detail.skillPoints" :key="item" class="flex items-start gap-2 rounded-xl bg-sky-50/80 px-3 py-2 text-xs leading-5 text-slate-700 ring-1 ring-sky-100"><CheckCircle2 class="mt-0.5 h-3.5 w-3.5 shrink-0 text-sky-600" /> {{ item }}</div></div></div><div class="rounded-[24px] border border-sky-200/70 bg-white/85 p-5"><div class="mb-4 flex items-center gap-2 text-sm font-semibold text-slate-900"><ShieldCheck class="h-4 w-4 text-sky-600" /> 适用场景</div><div class="rounded-2xl bg-sky-50/80 p-4 text-sm leading-6 text-slate-700 ring-1 ring-sky-200/70">{{ detail.scene }}</div></div><div class="rounded-[24px] border border-amber-200 bg-amber-50/80 p-5"><div class="mb-4 flex items-center gap-2 text-sm font-semibold text-amber-900"><AlertTriangle class="h-4 w-4" /> 本期边界</div><div class="space-y-2"><div v-for="item in detail.boundaries" :key="item" class="flex items-start gap-2 rounded-xl bg-white/70 px-3 py-2 text-xs leading-5 text-amber-900 ring-1 ring-amber-100"><CheckCircle2 class="mt-0.5 h-3.5 w-3.5 shrink-0" /> {{ item }}</div></div></div></aside></div>
  </div>
</template>
